font_family      Dank Mono
bold_font        Dank Mono, Bold
italic_font      Dank Mono, Italic
bold_italic_font auto
font_size 14.0
disable_ligatures never
cursor_blink_interval 0
open_url_modifiers ctl
window_alert_on_bell no
enable_audio_bell no
hide_window_decorations false
include themer-dark.conf
